const app=document.getElementById('app');
async function api(url,opt={}){const r=await fetch(url,{...opt,headers:{'content-type':'application/json',...(opt.headers||{})}});if(r.status===401){showLogin();throw Error('unauthorized')}const d=await r.json();if(!r.ok)throw Error(d.error||'Hiba');return d}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showLogin(msg=''){app.innerHTML=`<div class="login panel"><div class="brand">Tóvizi <span>Recruitment</span></div><h1>Admin belépés</h1><p class="muted">A weboldal üzenetei és személyre szabott linkjei innen kezelhetők.</p><div class="error">${esc(msg)}</div><input id="password" type="password" placeholder="Admin jelszó"><button class="btn" style="width:100%;margin-top:12px" id="login">Belépés</button></div>`;document.getElementById('login').onclick=login;document.getElementById('password').onkeydown=e=>{if(e.key==='Enter')login()};document.getElementById('password').focus()}
async function login(){try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({password:document.getElementById('password').value})});await dashboard()}catch{showLogin('Hibás jelszó.')}}
async function stats(){return api('/api/admin/stats')}
async function dashboard(){try{const s=await stats();app.innerHTML=`<div class="wrap"><div class="top"><div><div class="brand">Tóvizi <span>Recruitment</span></div><div class="muted">Admin felület</div></div><button class="btn light" id="logout">Kilépés</button></div><div class="grid"><div class="stat">Összes üzenet<b>${s.stats.total}</b></div><div class="stat">Olvasatlan<b>${s.stats.unread}</b></div><div class="stat">Kezelés alatt<b>${s.stats.progress}</b></div><div class="stat">Aktív link<b>${s.stats.links}</b></div></div><div class="tabs"><button class="tab active" data-t="messages">📩 Üzenetek</button><button class="tab" data-t="links">🔗 Személyre szabott linkek</button></div><section id="messages" class="panel"><div class="top"><div><h2>Beérkezett üzenetek</h2><div class="muted">Az űrlapról érkező megkeresések kezelése.</div></div><select id="filter"><option value="all">Minden státusz</option><option value="unread">Olvasatlan</option><option value="progress">Kezelés alatt</option><option value="closed">Lezárt</option></select></div><div id="messageList"></div></section><section id="links" class="panel hidden"><div class="top"><div><h2>Személyre szabott linkek</h2><div class="muted">6 számjegyű, egyedi URL-ek.</div></div><button class="btn" id="new">+ Új személy</button></div><div id="linkList"></div></section><div id="modal" class="hidden"></div></div>`;document.getElementById('logout').onclick=logout;document.getElementById('filter').onchange=messages;document.getElementById('new').onclick=newLink;document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>tab(b.dataset.t));await messages();await links()}catch{showLogin()}}
function tab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.t===id));document.getElementById('messages').classList.toggle('hidden',id!=='messages');document.getElementById('links').classList.toggle('hidden',id!=='links')}
async function messages(){const d=await api('/api/admin/messages?status='+encodeURIComponent(document.getElementById('filter').value));const l=document.getElementById('messageList');if(!d.items.length){l.innerHTML='<div class="empty">Nincs ilyen üzenet.</div>';return}l.innerHTML='<table><thead><tr><th>Dátum</th><th>Érdeklődő</th><th>Elérhetőség</th><th>Üzenet</th><th>Státusz</th><th>Műveletek</th></tr></thead><tbody>'+d.items.map(x=>`<tr><td>${esc(x.created_at)}</td><td><b>${esc(x.name)}</b><br><span class="muted">${esc(x.company||'')}</span></td><td>${esc(x.contact)}</td><td>${esc((x.message||'').slice(0,180))}</td><td><span class="pill">${x.status==='unread'?'Olvasatlan':x.status==='progress'?'Kezelés alatt':'Lezárt'}</span></td><td><div class="actions"><button class="btn light small" data-v="${x.id}">Megnyitás</button><button class="btn light small" data-p="${x.id}">Kezelés</button><button class="btn light small" data-c="${x.id}">Lezárás</button><button class="btn red small" data-d="${x.id}">Törlés</button></div></td></tr>`).join('')+'</tbody></table>';l.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>view(b.dataset.v));l.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>status(b.dataset.p,'progress'));l.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>status(b.dataset.c,'closed'));l.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>delMsg(b.dataset.d))}
async function status(id,s){await api('/api/admin/messages/'+id,{method:'PATCH',body:JSON.stringify({status:s})});await messages();await refreshStats()}
async function delMsg(id){if(!confirm('Biztosan törlöd ezt az üzenetet?'))return;await api('/api/admin/messages/'+id,{method:'DELETE'});await messages();await refreshStats()}
async function view(id){const d=await api('/api/admin/messages/'+id),x=d.item,m=document.getElementById('modal');m.className='modal';m.innerHTML=`<div class="modalbox"><div class="top"><h2>${esc(x.name)}</h2><button class="btn light" id="close">Bezárás</button></div><p><b>Cég:</b> ${esc(x.company||'—')}</p><p><b>Elérhetőség:</b> ${esc(x.contact)}</p><p><b>Érkezett:</b> ${esc(x.created_at)}</p><hr><p style="white-space:pre-wrap">${esc(x.message||'—')}</p></div>`;document.getElementById('close').onclick=()=>{m.className='hidden';m.innerHTML=''};if(x.status==='unread')await status(id,'progress')}
async function links(){const d=await api('/api/admin/links'),l=document.getElementById('linkList');if(!d.items.length){l.innerHTML='<div class="empty">Még nincs személyre szabott link.</div>';return}l.innerHTML='<table><thead><tr><th>Név</th><th>Link</th><th>Megnyitás</th><th>Utolsó megnyitás</th><th>Státusz</th><th>Műveletek</th></tr></thead><tbody>'+d.items.map(x=>`<tr><td><b>${esc(x.full_name)}</b><br><span class="muted">${esc(x.first_name)}</span></td><td><code>${esc(location.origin+'/'+x.code)}</code></td><td>${x.visit_count||0}</td><td>${esc(x.last_visit||'—')}</td><td><span class="pill">${x.active?'Aktív':'Deaktivált'}</span></td><td><div class="actions"><button class="btn light small" data-copy="${x.code}">Link másolása</button><button class="btn light small" data-tog="${x.id}" data-a="${x.active?0:1}">${x.active?'Deaktiválás':'Aktiválás'}</button><button class="btn red small" data-del="${x.id}">Törlés</button></div></td></tr>`).join('')+'</tbody></table>';l.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(b.dataset.copy));l.querySelectorAll('[data-tog]').forEach(b=>b.onclick=()=>toggle(b.dataset.tog,b.dataset.a));l.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>delLink(b.dataset.del))}
function newLink(){const m=document.getElementById('modal');m.className='modal';m.innerHTML='<div class="modalbox"><div class="top"><h2>Új személyre szabott link</h2><button class="btn light" id="x">Bezárás</button></div><div class="form"><div class="full"><label>Teljes név</label><input id="full" placeholder="Tóvizi Levente"></div><div class="full"><label>Megszólítás / keresztnév</label><input id="first" placeholder="Levente"></div></div><button class="btn" style="margin-top:14px" id="gen">Link generálása</button><div id="out" class="hidden"></div></div>';document.getElementById('x').onclick=()=>{m.className='hidden'};document.getElementById('gen').onclick=create}
async function create(){const full=document.getElementById('full').value.trim(),first=document.getElementById('first').value.trim();if(!full||!first)return alert('A teljes név és a keresztnév is szükséges.');const d=await api('/api/admin/links',{method:'POST',body:JSON.stringify({full_name:full,first_name:first})}),url=location.origin+'/'+d.code,o=document.getElementById('out');o.className='generated-link';o.innerHTML='<div><b>Elkészült a személyre szabott link</b></div><div class="generated-row"><input value="'+esc(url)+'" readonly><button class="btn" id="cp">Link másolása</button></div>';document.getElementById('cp').onclick=()=>copy(d.code);await links();await refreshStats()}
async function toggle(id,a){await api('/api/admin/links/'+id,{method:'PATCH',body:JSON.stringify({active:!!Number(a)})});await links();await refreshStats()}
async function delLink(id){if(!confirm('Biztosan törlöd ezt a linket?'))return;await api('/api/admin/links/'+id,{method:'DELETE'});await links();await refreshStats()}
async function copy(code){const u=location.origin+'/'+code;try{await navigator.clipboard.writeText(u);alert('Link kimásolva.')}catch{prompt('Másold ki a linket:',u)}}
async function refreshStats(){const s=await stats();document.querySelectorAll('.stat b')[0].textContent=s.stats.total;document.querySelectorAll('.stat b')[1].textContent=s.stats.unread;document.querySelectorAll('.stat b')[2].textContent=s.stats.progress;document.querySelectorAll('.stat b')[3].textContent=s.stats.links}
async function logout(){await api('/api/admin/logout',{method:'POST'});showLogin()}
dashboard();
